# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bno', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=50)),
                ('bauthor', models.CharField(max_length=20)),
                ('bpress', models.CharField(max_length=50)),
                ('status', models.DecimalField(decimal_places=0, default=1, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateTimeField()),
                ('rdate', models.DateTimeField()),
                ('rrdate', models.DateTimeField(null=True)),
                ('forfeit', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('flag', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='CCMSAdmin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('flag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_type', models.CharField(max_length=20)),
                ('con_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('con_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Guard_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('gateID', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('s_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('cardID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='west.Card')),
                ('open', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('cardID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='west.Card')),
                ('sign_in', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
        migrations.AddField(
            model_name='guard_record',
            name='cardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='west.Card'),
        ),
        migrations.AddField(
            model_name='consume',
            name='cardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='west.Card'),
        ),
        migrations.AddField(
            model_name='card',
            name='sno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='west.Student'),
        ),
        migrations.AddField(
            model_name='book_borrow',
            name='cardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='west.Card'),
        ),
        migrations.AddField(
            model_name='book_borrow',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='west.Book'),
        ),
    ]
